### ISSUE TITLE
Fix the page title

### ISSUE THREAD

**Issue by mahshidy** [maryamyasaei/Personal-Website-#3]
Right now it is: Nue Profile - Single page website.
This is the name that shows up in the browser tab
Maybe change it to. Maryam - Home

**Comment by maryamyasaei** [comment]
I changed , I cannot see the title and test if it is  good now or not . can you ??

**Comment by maryamyasaei** [comment]
in my browser shows maryamyasaei.com

**Comment by mahshidy** [comment]
Page title doesn't show up in the address bar. It goes on the tab. I have an attachment here that shows your previous page title and the new page title (Yes you have fixed it)
![screen shot 2017-07-11 at 8 34 12 am](https://user-images.githubusercontent.com/16924890/28068532-fef8b270-6613-11e7-9682-8895de025d87.png)

**Comment by maryamyasaei** [comment]
:D :D yup , just now seen that
