### ISSUE TITLE
Give a margin of 10 to the years in circles to make them middle aligned

### ISSUE THREAD

**Issue by mahshidy** [maryamyasaei/Personal-Website-#5]
![screen shot 2017-07-10 at 8 42 03 am](https://user-images.githubusercontent.com/16924890/28018564-d5050900-654b-11e7-836d-15df64f1c341.png)

**Comment by maryamyasaei** [comment]
I try !!!!!!!!!!!!

**Comment by maryamyasaei** [comment]
this photo means u did it yourself ? In this photo it is centre,  but I tried and gave margin , nothing changed !!!!!!

**Comment by mahshidy** [comment]
I opened the inspect element and gave a top margin to it there. So when you do that same which element do you give a top margin of 10 to?
