### ISSUE TITLE
Give a top margin of 4 and a left margin of 1 to the clock icon above the years to make it center aligned

### ISSUE THREAD

**Issue by mahshidy** [maryamyasaei/Personal-Website-#6]
![screen shot 2017-07-10 at 8 44 47 am](https://user-images.githubusercontent.com/16924890/28018672-2c38fb46-654c-11e7-9efd-e8a2ebd18d09.png)

**Comment by maryamyasaei** [comment]
I try!!!!!!!!

**Comment by maryamyasaei** [comment]
The same here !!!
