### ISSUE TITLE
The new photo is not properly aligned

### ISSUE THREAD

**Issue by mahshidy** [maryamyasaei/Personal-Website-#9]
![maryamhome](https://user-images.githubusercontent.com/16924890/28025547-ba355b46-6561-11e7-8d9f-0c80ad8b091f.png)

**Comment by mahshidy** [comment]
But this photo is really much better than the other ones you have :D

**Comment by maryamyasaei** [comment]
:D :D all of my photos are good , so make hard for me to choose :D :D

**Comment by maryamyasaei** [comment]
I think this issue is closed now, let me know if you think no !!!!!!

**Comment by maryamyasaei** [comment]
I changed the size of the photo and tested on my local server , it was aligned well but when I uploaded a new photo to Cpanel , it did not show any change !!!!!!

**Comment by maryamyasaei** [comment]
it worked , I think this issue is closed now :D
